# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.2"

[buildpack]
id       = "projectriff/node-function"
name     = "riff NodeJS Function Buildpack"
version  = "{{.version}}"
homepage = "https://github.com/projectriff/node-function-buildpack"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[metadata.configurations]]
name        = "RIFF"
description = "whether this is a riff function without a riff.toml file"
build       = true

[[metadata.configurations]]
name        = "RIFF_ARTIFACT"
description = "the artifact to invoke"
build       = true

[[metadata.dependencies]]
id      = "invoker"
name    = "riff NodeJS Invoker"
version = "0.3.0"
uri     = "https://storage.googleapis.com/projectriff/node-function-invoker/releases/v0.3.0/node-function-invoker-0.3.0.tgz"
sha256  = "83d4f64137aed4199c97031856ddcddf46cb2e173d805b46240d54d036d83241"
stacks  = [ "heroku-18", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/projectriff/node-function-invoker/blob/main/LICENSE"

[metadata]
pre-package   = "scripts/build.sh"
include-files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/detect",
  "bin/main",
  "buildpack.toml",
]
